webpsi/auth.py
# Copyright (C) 2023 Randogoth
#
# WebPsi is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# WebPsi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with WebPsi.  If not, see <https://www.gnu.org/licenses/>.

import pyrebase

from webpsi.config import FIREBASE_CONFIG

firebase = pyrebase.initialize_app(FIREBASE_CONFIG)
auth = firebase.auth()
person = {"is_logged_in": False, "name": "", "email": "", "uid": ""}

webpsi/views/classic_reg.py
# Copyright (C) 2020 AndieNoir
#
# WebPsi is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# WebPsi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with WebPsi.  If not, see <https://www.gnu.org/licenses/>.

import secrets
import threading
import time

from flask import Blueprint, render_template, request, redirect
from flask_breadcrumbs import register_breadcrumb
from geventwebsocket.websocket import WebSocket

from webpsi.utils import *
from webpsi.auth import person

_BYTES_PER_TRIAL = 25

blueprint = Blueprint('classic_reg', __name__)
ws_blueprint = Blueprint('classic_reg_ws', __name__)

create_logs_dir_if_not_exist()
_log_file = open('logs/classic_reg.csv', 'a')
if os.stat('logs/classic_reg.csv').st_size == 0:
    _log_file.write('dt,ip_address,user_id,run_id,trial_number,z_score,generator_id\n')
    _log_file.flush()

_generator = get_generator_instance()

_valid_run_ids = []


@blueprint.route('/')
@register_breadcrumb(blueprint, '.', 'Classic REG Experiment')
def classic_reg():
    if person["is_logged_in"] == True:
        return render_template('classic_reg.html')
    else:
        return redirect('/login')


@blueprint.route('/api/run_id')
def generate_run_id():
    run_id = secrets.token_bytes(4).hex()
    _valid_run_ids.append(run_id)
    return run_id


@ws_blueprint.route('/ws')
def ws(websocket: WebSocket):
    while not websocket.closed:
        split_message = websocket.receive().split()
        action = split_message[0].upper()
        if action == 'PING':
            _generator.get_bytes(_BYTES_PER_TRIAL)
            websocket.send('PONG')
        elif action == 'RUN':
            run_id = split_message[1]
            trial_count = int(split_message[2])
            if run_id in _valid_run_ids:
                threading.Thread(target=run_trials, args=(websocket, run_id, trial_count, request.remote_addr)).start()


def run_trials(websocket: WebSocket, run_id: str, trial_count: int, remote_addr: str):
    for i in range(trial_count):
        time.sleep(0.5)
        data = _generator.get_bytes(_BYTES_PER_TRIAL)
        gaussian = to_gaussian(data)
        websocket.send('GAUSSIAN %f' % gaussian)
        _log_file.write(f'{utc_datetime_string()},{remote_addr},{person["uid"]},{run_id},{i + 1},{gaussian:.3f},{_generator.id}\n')
        _log_file.flush()
    _valid_run_ids.remove(run_id)

webpsi/views/home.py
# Copyright (C) 2020 AndieNoir
#
# WebPsi is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# WebPsi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with WebPsi.  If not, see <https://www.gnu.org/licenses/>.

from flask import Blueprint, render_template, redirect
from flask_breadcrumbs import register_breadcrumb

blueprint = Blueprint('home', __name__)
from webpsi.auth import person

@blueprint.route('/')
@register_breadcrumb(blueprint, '.', 'Home')
def home():
    if person["is_logged_in"] == True:
        return render_template('home.html')
    else:
        return redirect('/login')

webpsi/views/login.py
# Copyright (C) 2020 Randogoth
#
# WebPsi is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# WebPsi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with WebPsi.  If not, see <https://www.gnu.org/licenses/>.

from flask import Blueprint, render_template
from flask_breadcrumbs import register_breadcrumb


blueprint = Blueprint('login', __name__)


@blueprint.route('/login')
@register_breadcrumb(blueprint, '.', 'Sign In')
def login():
    return render_template("login.html")

webpsi/views/singlebit_pk.py
# Copyright (C) 2020 AndieNoir
#
# WebPsi is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# WebPsi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with WebPsi.  If not, see <https://www.gnu.org/licenses/>.

import base64
import secrets

from flask import Blueprint, render_template, request, redirect
from flask_breadcrumbs import register_breadcrumb
from geventwebsocket.websocket import WebSocket

from webpsi.utils import *
from webpsi.auth import person

_BYTES_PER_TRIAL = 125

blueprint = Blueprint('singlebit_pk', __name__)
ws_blueprint = Blueprint('singlebit_pk_ws', __name__)

create_logs_dir_if_not_exist()
_log_file = open('logs/singlebit_pk.csv', 'a')
if os.stat('logs/singlebit_pk.csv').st_size == 0:
    _log_file.write('dt,ip_address,user_id,session_id,hit,raw_data,generator_id,generator_bit_numbering\n')
    _log_file.flush()

_generator = get_generator_instance()

_valid_session_ids = []


@blueprint.route('/')
@register_breadcrumb(blueprint, '.', 'Single-Bit PK Game')
def singlebit_pk():
    if person["is_logged_in"] == True:
        return render_template('singlebit_pk.html')
    else:
        return redirect('/login')


@blueprint.route('/api/session_id')
def generate_session_id():
    session_id = secrets.token_bytes(4).hex()
    _valid_session_ids.append(session_id)
    return session_id


@ws_blueprint.route('/ws')
def ws(websocket: WebSocket):
    while not websocket.closed:
        split_message = websocket.receive().split()
        action = split_message[0].upper()
        if action == 'RUN':
            session_id = split_message[1]
            if session_id in _valid_session_ids:
                data = _generator.get_bytes(_BYTES_PER_TRIAL)
                hit = to_bool(data, _generator.bit_numbering)
                websocket.send('HIT %d' % (1 if hit else 0))
                _log_file.write(f'{utc_datetime_string()},{request.remote_addr},{person["uid"]},{session_id},{hit},{base64.b64encode(data).decode("utf-8")},{_generator.id},{_generator.bit_numbering.value}\n')
                _log_file.flush()

webpsi/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{{ title }} | WebPsi</title>
  <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.3/gh-fork-ribbon.min.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style>
      .github-fork-ribbon:before {
        background-color: #fff;
      }

      .github-fork-ribbon:after {
        color: #1f1f1f;
        border-color: transparent;
      }
  </style>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('home.home') }}">Randonaut ESP Ψ Experiments</a><span id="credit">forked from <a href="https://github.com/AndieNoir/WebPsi">WebPsi</a> by AndieNoir</span>
  <a class="nav-link" href="/logout">Logout</a>
</nav>
{% if breadcrumbs|length > 1 %}
<nav>
  <ol class="breadcrumb">
    {% for breadcrumb in breadcrumbs %}
    <li class="breadcrumb-item {{ 'active' if loop.last }}">
      {% if not loop.last %}
      <a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a>
      {% else %}
      {{ breadcrumb.text }}
      {% endif %}
    </li>
    {% endfor %}
  </ol>
</nav>
{% endif %}
<main role="main" class="container mt-4 mb-4">
  {% block content %}{% endblock %}
</main>
</body>
</html>

webpsi/templates/classic_reg.html
{% extends 'base.html' %}
{% set title = 'Classic REG Experiment' %}

{% block content %}
<h3>{{ title }}</h3>
<div class="mt-4">
  The following random walk graph is generated using a quantum random number generator. If consciousness can
  influence quantum-level events, you should be able to influence the graph using your mind.
</div>
<div class="mt-4">
  <b>Try to make the graph to go up!</b>
</div>
<canvas class="mt-4" id="chart" style="border: thin solid #999; padding: 10px;"></canvas>
<div class="mt-4 text-center"><button class="btn btn-secondary" type="button" id="runButton" onclick="run()" >Run</button></div>
<table class="mt-4 stats">
  <tr>
    <td>P</td>
    <td>:</td>
    <td id="p">0.500</td>
  </tr>
  <tr>
    <td>Run ID</td>
    <td>:</td>
    <td id="runId" style="width: 9ch">-</td>
  </tr>
  <tr>
    <td>OWD</td>
    <td>:</td>
    <td id="owd">-</td>
  </tr>
</table>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jstat/1.9.3/jstat.min.js"></script>
<script>
    var TRIALS_PER_RUN = 30;

    var envelope_null = [];
    var envelope_top = [];
    var envelope_bottom = [];

    for (var i = 0; i < TRIALS_PER_RUN; i += 0.01) {
        envelope_null.push({x: i, y: 0});
        envelope_top.push({ x: i, y: 1.645 * Math.sqrt(i) });
        envelope_bottom.push({ x: i, y: -1.645 * Math.sqrt(i) });
    }

    var randomWalkData = [{ x: 0, y: 0 }];

    var chartContext = $('#chart');

    var chart = new Chart(chartContext, {
        type: 'scatter',
        data: {
            datasets: [
                {
                    data: envelope_null,
                    showLine: true,
                    pointRadius: 0,
                    fill: false,
                    lineTension: 0,
                    borderColor: 'grey',
                    borderWidth: 1,
                },
                {
                    data: envelope_top,
                    showLine: true,
                    pointRadius: 0,
                    fill: false,
                    lineTension: 0,
                    borderColor: 'cyan',
                    borderWidth: 1,
                    label: 'p = 0.05'
                },
                {
                    data: envelope_bottom,
                    showLine: true,
                    pointRadius: 0,
                    fill: false,
                    lineTension: 0,
                    borderColor: 'grey',
                    borderWidth: 1,
                },
                {
                    data: randomWalkData,
                    showLine: true,
                    pointRadius: 0,
                    fill: false,
                    lineTension: 0,
                    borderColor: 'white',
                    borderWidth: 1.5
                }
            ]
        },
        options: {
            legend: {
                labels: {
                    fontColor: '#999',
                    filter: function(label) {
                        if (label.text != null) return true;
                    }
                }
            },
            events: [],
            animation: {
                duration: 0
            },
            scales: {
                xAxes: [
                    {
                        position: 'bottom',
                        gridLines: {
                            display: false
                        },
                        ticks: {
                            max: TRIALS_PER_RUN,
                            min: 0,
                            stepSize: 10,
                            fontColor: '#999'
                        }
                    }
                ],
                yAxes: [
                    {
                        gridLines: {
                            display: false
                        },
                        ticks: {
                            max: 2 * envelope_top[envelope_top.length - 1]['y'],
                            min: -1.5 * envelope_top[envelope_top.length - 1]['y'],
                            display: false
                        }
                    }
                ]
            }
        }
    });

    if (location.protocol !== 'https:') {
        var websocket = new WebSocket(document.location.href.replace('http://', 'ws://').replace(/\/$/, '') + '/ws');
    } else {
        var websocket = new WebSocket(document.location.href.replace('https://', 'wss://').replace(/\/$/, '') + '/ws');
    }

    var owdData = [];

    var pingSentTime;

    websocket.onmessage = function(event) {
        var splitMessage = event.data.split(' ');
        var messageType = splitMessage[0].toUpperCase();
        if (messageType === 'PONG') {
            owdData.push((performance.now() - pingSentTime) / 2);
            if (owdData.length < 5) {
                setTimeout(function() {
                    websocket.send('PING');
                    pingSentTime = performance.now()
                }, 100);
            } else {
                $('#owd').html(Math.round(jStat.mean(owdData)) + ' ms');
                owdData.length = 0;
                $.get('api/run_id', function(runId) {
                    $('#runId').html(runId);
                    websocket.send('RUN ' + runId + ' ' + TRIALS_PER_RUN)
                });
            }
        } else if (messageType === 'GAUSSIAN') {
            var gaussian = parseFloat(splitMessage[1]);
            randomWalkData.push({ x: randomWalkData.length, y: randomWalkData[randomWalkData.length - 1]['y'] + gaussian });
            chart.update();
            var x = randomWalkData[randomWalkData.length - 1]['y'] / Math.sqrt(randomWalkData.length);
            var p = 1 - jStat.normal.cdf(x, 0, 1);
            $('#p').html(p.toFixed(3));
            if (randomWalkData.length - 1 >= TRIALS_PER_RUN) {
                $('#runButton').prop('disabled', false);
            }
        }
    };

    function run() {
        $('#runButton').prop('disabled', true);
        randomWalkData.length = 0;
        randomWalkData.push({ x: 0, y: 0 });
        chart.update();
        websocket.send('PING');
        pingSentTime = performance.now()
    }
</script>
{% endblock %}

webpsi/templates/home.html
{% extends 'base.html' %}
{% set title = 'Home' %}

{% block content %}
<h5>Experiments</h5>
<div class="list-group mt-4">
  <a href="classic_reg" class="list-group-item list-group-item-action">Classic REG</a>
  <a href="singlebit_pk" class="list-group-item list-group-item-action">Single-Bit PK Game</a>
</div>
{% endblock %}

webpsi/templates/login.html
{% extends 'base.html' %}
{% set title = 'Sign In' %}

{% block content %}
<h5>Sign In </h5>
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Login Form -->
    <form action="/result" method="POST">
      <div class="form-row">
        <div class="form-group col-md-4">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" id="login" class="form-control fadeIn second" name="email" placeholder="email">
          <small id="emailHelp" class="form-text text-muted">The same you use for the Randonautica app</small>
        </div>
        <div class="form-group col-md-4">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" id="password" class="form-control fadeIn third" name="pass" placeholder="password">
        </div>
      </div>
      <button type="submit" class="btn btn-primary fadeIn fourth">Sign In</button>
      <button type="submit" name="anonymous" class="btn btn-secondary fadeIn fourth" value="true">Continue Anonymously</button>
    </form>
  </div>
</div>
{% endblock %}

webpsi/templates/singlebit_pk.html
{% extends 'base.html' %}
{% set title = 'Single-Bit PK Game' %}

{% block content %}
<h3>{{ title }}</h3>
<div class="mt-4">
  By clicking the run button, a quantum random number generator will be used to color the box below with red or green.
  If consciousness can influence quantum-level events, you should be able to influence the color.
</div>
<div class="mt-4">
  <b>Try to make it green!</b>
</div>
<div id="box" class="mt-4" style="width: 150px; height: 150px; margin-left: auto; margin-right: auto; border: thin solid #fff; border-radius: 10px"></div>
<div class="mt-4 text-center"><button class="btn btn-secondary" type="button" id="runButton" onclick="run()">Run</button></div>
<table class="mt-4 stats">
  <tr>
    <td>Trial count</td>
    <td>:</td>
    <td id="trialCount">0</td>
  </tr>
  <tr>
    <td>Hit rate</td>
    <td>:</td>
    <td id="hitRate">-</td>
  </tr>
  <tr>
    <td>P</td>
    <td>:</td>
    <td id="p">-</td>
  </tr>
  <tr>
    <td>Session ID</td>
    <td>:</td>
    <td id="sessionId" style="width: 9ch">-</td>
  </tr>
  <tr>
    <td>RTD</td>
    <td>:</td>
    <td id="rtd">-</td>
  </tr>
</table>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jstat/1.9.3/jstat.min.js"></script>
<script>
    var sessionId = null;

    $.get('api/session_id', function(data) {
        sessionId = data;
        $('#sessionId').html(sessionId);
    });

    var trials = [];

    if (location.protocol !== 'https:') {
        var websocket = new WebSocket(document.location.href.replace('http://', 'ws://').replace(/\/$/, '') + '/ws');
    } else {
        var websocket = new WebSocket(document.location.href.replace('https://', 'wss://').replace(/\/$/, '') + '/ws');
    }

    var requestSentTime;

    websocket.onmessage = function(event) {
        var splitMessage = event.data.split(' ');
        var messageType = splitMessage[0].toUpperCase();
        if (messageType === 'HIT') {
            var rtd = performance.now() - requestSentTime;
            var hit = parseInt(splitMessage[1]);
            if (hit === 1) {
                $('#box').css('backgroundColor', '#0f0');
            } else {
                $('#box').css('backgroundColor', '#f00');
            }
            trials.push(hit);
            var hitCount = trials.filter(function(trial) { return trial === 1 }).length;
            var hitRate = hitCount / trials.length;
            var p = 1 - jStat.binomial.cdf(hitCount - 1, trials.length, 0.5);
            $('#trialCount').html(trials.length);
            $('#hitRate').html(Math.round(hitRate * 100) + "%");
            $('#p').html(p.toFixed(3));
            $('#rtd').html(Math.round(rtd) + ' ms');
            $('#runButton').prop('disabled', false);
        }
    };

    function run() {
        $('#runButton').prop('disabled', true);
        websocket.send('RUN ' + sessionId);
        requestSentTime = performance.now();
    }
</script>
{% endblock %}